# Generated by Django 3.1.4 on 2020-12-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate',
            field=models.FileField(max_length=254, upload_to='certificates'),
        ),
    ]
