# Generated by Django 3.1.4 on 2020-12-10 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_certificate', '0002_auto_20201210_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificateTitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
