# Generated by Django 3.1.4 on 2020-12-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TesteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileTest', models.FileField(max_length=254, upload_to='certificates')),
            ],
        ),
    ]
