# Generated by Django 3.1.4 on 2020-12-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0002_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
